# Generated by Django 5.2.15 on 2026-06-12 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='pets_uploaded/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
