# Generated by Django 6.0.6 on 2026-06-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_report_id', models.IntegerField()),
                ('found_report_id', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False, help_text='Confirmado por los usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(help_text='ID del reporte de la mascota en el otro servicio', unique=True)),
                ('pet_type', models.CharField(help_text='perro, gato, etc.', max_length=50)),
                ('ai_description', models.TextField(help_text='Descripción detallada generada automáticamente por Gemini')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
