# Generated by Django 4.2 on 2026-04-20 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('radio_km', models.FloatField()),
                ('reportes_cercanos', models.TextField(blank=True)),
                ('fecha_cache', models.DateTimeField(auto_now=True)),
                ('valido', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_cache'],
            },
        ),
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('latitud_centro', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud_centro', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radio_km', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('zona_tipo', models.CharField(choices=[('barrio', 'Barrio'), ('ciudad', 'Ciudad'), ('region', 'Región'), ('personalizada', 'Personalizada')], default='personalizada', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte_id', models.CharField(help_text='ID único del reporte', max_length=100, unique=True)),
                ('pet_id', models.CharField(help_text='ID de la mascota', max_length=100)),
                ('usuario_id', models.IntegerField(blank=True, help_text='ID del usuario que creó el reporte', null=True)),
                ('latitud', models.FloatField(help_text='Latitud WGS84', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.FloatField(help_text='Longitud WGS84', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_reporte', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], default='perdido', max_length=20)),
                ('tipo_animal', models.CharField(blank=True, max_length=50)),
                ('raza_probable', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('tamaño', models.CharField(blank=True, choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['reporte_id'], name='geo_app_loc_reporte_672646_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['pet_id'], name='geo_app_loc_pet_id_2e45db_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tipo_reporte'], name='geo_app_loc_tipo_re_499033_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geocache',
            unique_together={('latitud', 'longitud', 'radio_km')},
        ),
    ]
