# Generated by Django 4.2 on 2026-05-09 03:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-fecha_reporte'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.RemoveIndex(
            model_name='location',
            name='geo_app_loc_pet_id_2e45db_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='reporte_id_idx',
            old_name='geo_app_loc_reporte_672646_idx',
        ),
        migrations.RenameIndex(
            model_name='location',
            new_name='tipo_reporte_idx',
            old_name='geo_app_loc_tipo_re_499033_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='color',
            field=models.CharField(blank=True, help_text='Color para matching', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='fecha_reporte',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha del reporte original'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitud',
            field=models.FloatField(help_text='Latitud en WGS84', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitud',
            field=models.FloatField(help_text='Longitud en WGS84', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='pet_id',
            field=models.CharField(db_index=True, help_text='ID de la mascota (Pet Service)', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='raza_probable',
            field=models.CharField(blank=True, help_text='Raza probable para matching', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='reporte_id',
            field=models.CharField(db_index=True, help_text='ID único del reporte (Pet Service)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='tamaño',
            field=models.CharField(blank=True, choices=[('pequeño', 'Pequeño (0-10 kg)'), ('mediano', 'Mediano (10-30 kg)'), ('grande', 'Grande (30-50 kg)'), ('muy_grande', 'Muy Grande (50+ kg)')], help_text='Tamaño para matching', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='tipo_animal',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('pajaro', 'Pájaro'), ('conejo', 'Conejo'), ('otro', 'Otro')], help_text='Tipo de animal para matching', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='tipo_reporte',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], db_index=True, help_text='Tipo de reporte: perdido o encontrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='usuario_id',
            field=models.CharField(blank=True, db_index=True, help_text='UUID del usuario que creó el reporte (Auth Service)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitud', 'longitud'], name='location_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['usuario_id'], name='usuario_id_idx'),
        ),
    ]
