# Generated by Django 6.0.3 on 2026-05-09 07:20

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', help_text='Formato: 9 XXXX XXXX o +56 9 XXXX XXXX', max_length=20, validators=[users.validators.validate_chilean_phone]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rut',
            field=models.CharField(default='', help_text='Formato: 12345678-9 o 12.345.678-9', max_length=12, unique=True, validators=[users.validators.validate_chilean_rut]),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
